// <auto-generated />
using System;
using DistributedExceptionHandler.Repositories;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace DistributedExceptionHandler.Migrations
{
    [DbContext(typeof(ExceptionDataContext))]
    partial class ExceptionDataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("DistributedExceptionHandler.Models.ExceptionModel", b =>
                {
                    b.Property<Guid>("ExceptionGuid")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Code");

                    b.Property<string>("Detail");

                    b.Property<DateTime>("ExceptionConsumedDate");

                    b.Property<DateTime>("ExceptionDate");

                    b.Property<string>("Origin")
                        .IsRequired();

                    b.Property<string>("StatusCode");

                    b.Property<string>("Type")
                        .IsRequired();

                    b.HasKey("ExceptionGuid");

                    b.ToTable("ExceptionModels");
                });
#pragma warning restore 612, 618
        }
    }
}
